# This file contains all the prompts of the of print and input statements used in the project
---
# file paths
database_path : src\\database\\parking_management.db
logs_file_path : src\\logs\\logs.txt

# app module prompts
welcome_message : ----Welcome to Vehicle Parking Management System----
exit_message : ----Thank you for using the system. Hope you had a great experience----

# common prompts
maximum_login_attempts : 3
enter_choice : "Enter your choice (in integer) : " 
invalid_input : Invalid input...Try again
input_username : "Username : "
input_name : "Name : "
input_mobile_number : "Mobile No. : "
zero_record : 0 records found in {} table. Please enter some records!
details_does_not_exist : "{} does not exist..."
new_detail_input : Enter new {}...
successful_logout : Logout of the system successful...
cannot_perform_updation : Cannot perform updation. Enter correct data.

# authentication module prompts
input_credential : "Enter your credentials : "
input_password : "Password : "
successful_login : Login Successful...
login_attempts_left : |
  Invalid login...
  Login attempts left : {}
login_attempts_exhausted : Login attempts exhausted! Please login after some time...
change_password : Change your password...
input_new_password : "New Password : "
input_confirm_password : "Confirm Password : "
password_not_match : Password does not match. Please enter your password again!
password_change_successful : Password changed successfully! Now login with your new password...

# admin_controller module prompts
input_employee_details : Enter employee details...
input_employee_age : "Age : "
input_employee_gender : "Enter F for Female and M for Male : "
input_employee_role : "Enter role : "
input_employee_email: "Email Address : "
user_already_exist : "{} already exist. Try Again!"
employee_registration_successful : Employee registered successfully...
no_default_password : No default password exist...Password has been already changed
print_default_password : The default password for given employee is {}
input_details_for_removal : Enter below detail to remove record...
update_details_for_inactive_status : Cannot update details for given record as the record is not active...
employee_removal_successful : Employee removed successfully...
input_details_for_updation : Enter below detail to update record...
employee_updation_successful : Employee details updated successfully...
create_user_credentials : Create user credentials...
not_valid_username : Please enter a valid username
not_valid_role : Please enter a valid role

# employee_name_input : "Name : "
employee_mobile_no_input : "Mobile No. : "
details_for_given_employee : "The details for given employee with emp_id : {} are..."
cannot_input_past_date : You entered a date that has been already passed. Please enter a valid date for out_date.

# prompts for validator
username_format : Username should be starting with 'user@'
cannot_create_admin : You cannot create admin. Please enter some other role
age_restriction : Age should be greater than 15 and less than 60
number_input : "{} is expected to be a number. Please enter correct input"
vehicle_number_format : Vehcile number should be in the format 'MH-02-VD-9874'

# helpers module prompts
strong_password_requirements : |
  Please enter a password following below requirements:
  1. Password length should be 8 characters or more.
  2. Password must contain at least one uppercase character.
  3. Password must contain at least one lowercase character.
  4. Password must contain at leat one digit.
  5. Password must contain at least one of the given special character : @, #, $, %, &
weak_password_input : You entered a weak password...Please follow mentioned instructions to create a strong password.

# vehicle_type module prompts
input_type_name : "Enter a category for vehicle : "
input_price : "Enter price per hour for the category : "
vehicle_type_registration_successful : Vehicle type registered successfully...
vehicle_type_details_updation_successful : Vehicle type details updated successfully...
vehicle_type_removal_successful : Vehicle type removed successfully...
input_type_id : "Type ID : "
vehicle_type_does_not_exist : Entered vehicle type does not exist or is inactive...
vehicle_type_already_exist : Entered vehcile type already exist...
typeid_does_not_exist : Entered Type ID does not exist. Please enter correct Type ID...
current_price_per_hour : "Current price per hour is : {}"

# parking_slot module prompts
input_parking_slot_number : "Parking Slot No. : "
parking_slot_registration_successful : Parking slot number registered successfully...
parking_slot_activation_successful : Parking slot number activated successfully...
parking_slot_updation_successful : Parking slot number details updated successfully...
parking_slot_removal_successful : Parking slot number removed successfully...
parking_slot_number_already_exist : Parking slot number already exist. Please enter a new parking slot number...
parking_slot_number_does_not_exist : Parking slot number does not exist. Please enter correct parking slot number...
parking_slot_deactivation_successful : Parking slot deactivated successfully...
parking_slot_deletion_successful : Parking slot deleted successfully...
parking_slot_already_vacant : Parking slot is already vacant. Please enter correct parking slot number.
parking_slot_inactive : Parking slot is inactive. Cannot update status.
parking_slot_deleted :  Parking slot is deleted. Cannot update status.

# employee_controller module prompts
customer_details_input : Enter customer details...
vehicle_number_input : "Vehicle No. : "
customer_creation_successful : Customer registered successfully...
customer_already_exist : Customer already exist. Please enter new customer...
customer_does_not_exist : Customer does not exist with the vehicle no. Please enter correct vehicle no...
customer_updation_successful : Customer data updated successfully...

# slot_booking module prompts
customer_out_date_input : "Enter customer out date as DD-MM-YYYY format : "
input_details_for_slot_booking : Enter below details of customer for slot booking...
vehicleno_not_found : Record for given vehicle no not exist. Please regsiter the customer first.
parking_slot_assigned : "Parking slot assigned is : {}"
booking_records_not_found : Booking records for given customer not found. Please book a parking slot...
no_updation_for_check_out_vehicle : Given vehicle has already left parking slot. No updations can be done...
slot_booking_updation_successful : Slot booking data updated successfully...
input_booking_id : "Booking ID : "
parking_slot_vacant : Parking slot vacanted successfully...

# parking_charges prompts
print_parking_charges : Your parking charge is {} for {} hours spent in parking...

# query executor module prompts
integrity_error_message : You entered data that already exist. Please enter unique data.
operational_error_message : Something unexpected happened with the Database. Please try again after some time.
programming_error_message : Something wrong with the code on backend. Please wait while we resolve the issue.
general_exception_message : |
  We are encountering some issue in the backend side. 
  We will be back soon. 
  Thank you for waiting...
...